import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../api/axios';
import AppShell from '../components/AppShell';
import Icon from '../components/Icon';

const splitSkills = (value) => value.split(',').map((item) => item.trim()).filter(Boolean);
const parseAvailability = (text) => {
  const days = ['monday','tuesday','wednesday','thursday','friday','saturday','sunday']; const time = /^([01]\d|2[0-3]):[0-5]\d$/; const slots=[]; const errors=[];
  text.split(',').map((item)=>item.trim()).filter(Boolean).forEach((entry)=>{ const match=entry.match(/^(\w+)\s+(\d{1,2}:\d{2})-(\d{1,2}:\d{2})$/); if(!match){errors.push(`Use "day HH:MM-HH:MM" for "${entry}".`);return;} const [,day,start,end]=match; if(!days.includes(day.toLowerCase())){errors.push(`"${day}" is not a valid day.`);return;} if(!time.test(start)||!time.test(end)){errors.push(`Use 24-hour times for "${entry}".`);return;} slots.push({day:day.toLowerCase(),start,end}); }); return {slots,errors};
};

function EditSkills(){
  const [form,setForm]=useState({skillsOffered:'',skillsWanted:'',bio:'',city:'',country:'',timezone:'UTC',availability:''}); const [message,setMessage]=useState(''); const [isSaving,setIsSaving]=useState(false); const [loading,setLoading]=useState(true); const navigate=useNavigate();
  useEffect(()=>{let active=true;api.get('/users/me').then(({data:p})=>{if(active)setForm({skillsOffered:(p.skillsOffered||[]).join(', '),skillsWanted:(p.skillsWanted||[]).join(', '),bio:p.bio||'',city:p.location?.city||'',country:p.location?.country||'',timezone:p.timezone||'UTC',availability:(p.availability||[]).map((s)=>`${s.day} ${s.start}-${s.end}`).join(', ')});}).catch(()=>{if(active)setMessage('Failed to load your profile.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
  const update=(key,value)=>setForm((current)=>({...current,[key]:value})); const offered=useMemo(()=>splitSkills(form.skillsOffered),[form.skillsOffered]); const wanted=useMemo(()=>splitSkills(form.skillsWanted),[form.skillsWanted]);
  const handleSubmit=async(event)=>{event.preventDefault();setMessage('');const {slots,errors}=parseAvailability(form.availability);if(errors.length){setMessage(errors[0]);return;}setIsSaving(true);try{await Promise.all([api.put('/users/me/skills',{skillsOffered:offered,skillsWanted:wanted}),api.put('/users/me/profile',{bio:form.bio,timezone:form.timezone,location:{city:form.city,country:form.country},availability:slots})]);setMessage('Profile saved successfully.');setTimeout(()=>navigate('/dashboard'),700);}catch(err){setMessage(err.response?.data?.message||'Update failed.');}finally{setIsSaving(false);}};
  return <AppShell eyebrow="Profile studio" title="Make your experience stand out." description="A complete profile helps the right learners find you and makes every exchange feel more personal.">
    <div className="profile-editor">
      <form className="surface profile-form" onSubmit={handleSubmit} aria-busy={loading}>
        {message&&<p className={`status-message ${message.includes('failed')||message.includes('Use ')||message.includes('valid')?'error':''}`}>{message}</p>}
        <section className="form-section"><div className="form-section-head"><span>01</span><div><h2>About you</h2><p>Give the community a warm introduction.</p></div></div><div className="form-field"><label htmlFor="bio">Short bio</label><textarea id="bio" value={form.bio} onChange={(e)=>update('bio',e.target.value)} placeholder="What do you enjoy teaching, learning, or making?" maxLength="500"/><span className="form-hint">{form.bio.length}/500 characters</span></div></section>
        <section className="form-section"><div className="form-section-head"><span>02</span><div><h2>Your skills</h2><p>Separate each skill with a comma.</p></div></div><div className="form-field"><label htmlFor="skills-offered">Skills you can teach</label><input id="skills-offered" value={form.skillsOffered} onChange={(e)=>update('skillsOffered',e.target.value)} placeholder="Guitar, Excel, Cooking"/>{offered.length>0&&<div className="skill-tags">{offered.map((skill)=><span className="skill-tag" key={skill}>{skill}</span>)}</div>}</div><div className="form-field"><label htmlFor="skills-wanted">Skills you want to learn</label><input id="skills-wanted" value={form.skillsWanted} onChange={(e)=>update('skillsWanted',e.target.value)} placeholder="Spanish, Photography"/>{wanted.length>0&&<div className="skill-tags wanted-tags">{wanted.map((skill)=><span className="skill-tag" key={skill}>{skill}</span>)}</div>}</div></section>
        <section className="form-section"><div className="form-section-head"><span>03</span><div><h2>Location and availability</h2><p>Help people suggest times that work.</p></div></div><div className="form-columns"><div className="form-field"><label htmlFor="city">City</label><input id="city" value={form.city} onChange={(e)=>update('city',e.target.value)} placeholder="Dhaka"/></div><div className="form-field"><label htmlFor="country">Country</label><input id="country" value={form.country} onChange={(e)=>update('country',e.target.value)} placeholder="Bangladesh"/></div></div><div className="form-field"><label htmlFor="timezone">Timezone</label><input id="timezone" value={form.timezone} onChange={(e)=>update('timezone',e.target.value)} placeholder="Asia/Dhaka"/></div><div className="form-field"><label htmlFor="availability">Weekly availability</label><input id="availability" value={form.availability} onChange={(e)=>update('availability',e.target.value)} placeholder="monday 18:00-20:00, saturday 10:00-12:00"/><span className="form-hint">Use 24-hour time: day HH:MM-HH:MM, separated by commas.</span></div></section>
        <div className="form-footer"><button className="ghost-button" type="button" onClick={()=>navigate('/dashboard')}>Cancel</button><button className="primary-button" type="submit" disabled={isSaving||loading}>{isSaving?'Saving profile...':'Save changes'}<Icon name="arrow" size={15}/></button></div>
      </form>
      <aside className="profile-preview"><p className="section-kicker">Live preview</p><div className="surface preview-card"><span className="preview-avatar">{form.bio?form.bio.slice(0,1).toUpperCase():'S'}</span><span className="preview-label">Community profile</span><h2>{form.city||form.country?[form.city,form.country].filter(Boolean).join(', '):'Your location'}</h2><p>{form.bio||'Your bio will appear here as you write it.'}</p><div><small>Teaching</small><div className="skill-tags">{offered.length?offered.slice(0,4).map((skill)=><span className="skill-tag" key={skill}>{skill}</span>):<span className="form-hint">Add your first skill</span>}</div></div></div><div className="profile-tip"><Icon name="spark"/><div><strong>Profile tip</strong><p>Specific skills and a friendly bio lead to better matches.</p></div></div></aside>
    </div>
  </AppShell>;
}
export default EditSkills;
