import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../api/axios';
import AppShell from '../components/AppShell';

function EditSkills() {
  const [form, setForm] = useState({ skillsOffered: '', skillsWanted: '', bio: '', city: '', country: '', timezone: 'UTC', availability: '' });
  const [message, setMessage] = useState('');
  const [isSaving, setIsSaving] = useState(false);
  const navigate = useNavigate();
  useEffect(() => { let cancelled = false; api.get('/users/me').then((res) => { if (!cancelled) { const profile = res.data; setForm({ skillsOffered: (profile.skillsOffered || []).join(', '), skillsWanted: (profile.skillsWanted || []).join(', '), bio: profile.bio || '', city: profile.location?.city || '', country: profile.location?.country || '', timezone: profile.timezone || 'UTC', availability: (profile.availability || []).map((slot) => `${slot.day} ${slot.start}-${slot.end}`).join(', ') }); } }).catch(() => { if (!cancelled) setMessage('Failed to load profile'); }); return () => { cancelled = true; }; }, []);
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const handleSubmit = async (event) => { event.preventDefault(); setMessage(''); setIsSaving(true); try { const availability = form.availability.split(',').map((item) => item.trim()).filter(Boolean).map((item) => { const [day, range] = item.split(/\s+/); const [start, end] = (range || '').split('-'); return { day: day.toLowerCase(), start, end }; }).filter((slot) => slot.day && slot.start && slot.end); await Promise.all([api.put('/users/me/skills', { skillsOffered: form.skillsOffered.split(',').map((skill) => skill.trim()).filter(Boolean), skillsWanted: form.skillsWanted.split(',').map((skill) => skill.trim()).filter(Boolean) }), api.put('/users/me/profile', { bio: form.bio, timezone: form.timezone, location: { city: form.city, country: form.country }, availability })]); setMessage('Profile updated!'); setTimeout(() => navigate('/dashboard'), 900); } catch (err) { setMessage(err.response?.data?.message || 'Update failed'); } finally { setIsSaving(false); } };
  return <AppShell eyebrow="Your skill profile" title="Shape your exchange." description="Tell the community what you can share, where you are, and when you are available."><div className="surface form-card"><p className="section-kicker">Your public profile</p>{message && <p className="status-message">{message}</p>}<form onSubmit={handleSubmit}><div className="form-field"><label htmlFor="bio">Short bio</label><textarea id="bio" value={form.bio} onChange={(event) => update('bio', event.target.value)} placeholder="What are you curious about?" /></div><div className="form-field"><label htmlFor="skills-offered">Skills I can teach</label><input id="skills-offered" value={form.skillsOffered} onChange={(event) => update('skillsOffered', event.target.value)} placeholder="Guitar, Excel, Cooking" /></div><div className="form-field"><label htmlFor="skills-wanted">Skills I want to learn</label><input id="skills-wanted" value={form.skillsWanted} onChange={(event) => update('skillsWanted', event.target.value)} placeholder="Spanish, Photography" /></div><div className="content-grid two-column"><div className="form-field"><label htmlFor="city">City</label><input id="city" value={form.city} onChange={(event) => update('city', event.target.value)} placeholder="Dhaka" /></div><div className="form-field"><label htmlFor="country">Country</label><input id="country" value={form.country} onChange={(event) => update('country', event.target.value)} placeholder="Bangladesh" /></div></div><div className="form-field"><label htmlFor="timezone">Timezone</label><input id="timezone" value={form.timezone} onChange={(event) => update('timezone', event.target.value)} placeholder="Asia/Dhaka" /></div><div className="form-field"><label htmlFor="availability">Availability</label><input id="availability" value={form.availability} onChange={(event) => update('availability', event.target.value)} placeholder="monday 18:00-20:00, saturday 10:00-12:00" /><span className="form-hint">Use day and time ranges separated by commas.</span></div><div className="stack-actions"><button className="primary-button" type="submit" disabled={isSaving}>{isSaving ? 'Saving...' : 'Save profile'} <span>→</span></button><button className="secondary-button" type="button" onClick={() => navigate('/dashboard')}>Cancel</button></div></form></div></AppShell>;
}

export default EditSkills;
