export const FAQ = [
  ['What is SkillSwap?', 'A marketplace for live one-to-one video lessons in technology: programming, cloud, data and AI, cybersecurity and more. Every teacher is a verified university lecturer, industry professional, certified trainer or independent expert.'],
  ['How do credits work?', 'Credits are the currency of the platform. New members get 5 free credits. You can buy more any time, and credits never expire. Each teacher sets an hourly price in credits (most are 1 to 3 credits per hour), and a session costs that rate for the booked length: 30 minutes is half the hourly price.'],
  ['How are teachers verified?', 'Every applicant submits proof: a degree, certification, employment or published work, plus links a reviewer can open. Lecturers and employees can also verify a university or work mailbox with a one-time code. A SkillSwap reviewer checks everything by hand before anyone can be booked, and can remove access at any time.'],
  ['Who can become a teacher?', 'University lecturers and researchers, working software, data and security professionals, certified trainers, and independent experts such as open-source maintainers. You need at least a year of experience, verifiable proof, and skills from our tech catalog.'],
  ['Can I get a refund if my teacher does not show up?', 'You are only charged for sessions that actually take place. Credits are held when a teacher confirms a session. If the teacher never joins, the hold is released automatically and the credits go back to your wallet.'],
  ['When does the teacher get paid?', 'When the learner confirms the session. If the learner forgets, the session settles automatically 24 hours later, as long as both of you were in the room. Earnings can be withdrawn after a short clearing period of three days.'],
  ['How do teachers cash out?', 'Teachers connect their bank account through Stripe once, then withdraw earned credits at a fixed rate per credit, from a $20 minimum. Large withdrawals are reviewed by our team before they are sent. Free credits and credits you bought for learning cannot be withdrawn, only credits earned by teaching.'],
  ['What does SkillSwap charge?', 'Learners pay the price of the session in credits. Teachers pay a platform fee on what they earn: 12% on the Free plan and 6% on Pro. There are no listing fees, and applying to teach is free.'],
  ['What does Pro include?', 'Half the platform fee for teachers, one bonus credit every month, up to 25 active bookings, sessions up to four hours, and priority placement in Discover. Cancel any time from your billing page.'],
  ['What do I need for a video session?', 'A modern browser (Chrome, Edge, Firefox or Safari), a camera and microphone. There is nothing to install. The room opens 10 minutes before the scheduled start. Screen sharing and chat are built in.'],
  ['Are sessions recorded?', 'No. Video and audio travel directly between the two participants, encrypted in transit, and SkillSwap never records or stores them. In-call chat messages are saved to your conversation so you can refer back to links and notes.'],
  ['Is my location shared?', 'Never your exact position. Location is optional and only used to rank nearby teachers; other people see at most the city you choose to show. Sessions are always online.']
];
