name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  backend-check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: npm test


  frontend-check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci

      - run: npm run lint

      - run: npm run build


  matching-service-check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./matching-service

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt

      - run: python -m unittest -v

  notification-service-check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./notification-service

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt

      - run: python -m unittest -v

  docker-compose-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: docker compose config
